### ISSUE TITLE
NFS Server Instructions May Need an Update

### ISSUE THREAD

**Issue by julienchastang** [zonca/jupyterhub-deploy-kubernetes-jetstream#56] opened 2023-02-06 05:18 UTC
I've been following the steps for an NFS server here: https://www.zonca.dev/posts/2020-07-10-nfs-server-kubernetes-jetstream.html

But these instructions may need an update as I am seeing the following warning:

```
$ kubectl create -f create_nfs_volume.yaml
persistentvolumeclaim/nfs-share-folder-claim created
[openstack@12769e052f2e nfs]$ kubectl get pvc --all-namespaces
NAMESPACE   NAME                     STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
default     nfs-share-folder-claim   Pending                                                                        standard       2s
jhub        claim-xxx    Bound     pvc-b217661e-042f-4fa2-8d11-581c36722804   10Gi       RWO            cinder-csi     40m
jhub        hub-db-dir               Bound     pvc-090a6993-3006-4e9e-beb4-a9d73f8adbe0   1Gi        RWO            cinder-csi     42m
[openstack@12769e052f2e nfs]$ kubectl describe pvc nfs-share-folder-claim
Name:          nfs-share-folder-claim
Namespace:     default
StorageClass:  standard
Status:        Pending
Volume:
Labels:        <none>
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason              Age               From                         Message
  ----     ------              ----              ----                         -------
  Warning  ProvisioningFailed  8s (x2 over 18s)  persistentvolume-controller  storageclass.storage.k8s.io "standard" not found
```

Also, subsequent steps to create the server  yield additional warnings:

```
$ k describe pods nfs-server-76d648b554-4g6kj
Name:             nfs-server-76d648b554-4g6kj
Namespace:        default
Priority:         0
Service Account:  default
Node:             <none>
Labels:           pod-template-hash=76d648b554
                  role=nfs
Annotations:      <none>
Status:           Pending
IP:
IPs:              <none>
Controlled By:    ReplicaSet/nfs-server-76d648b554
Containers:
  nfs-server:
    Image:      itsthenetwork/nfs-server-alpine
    Port:       <none>
    Host Port:  <none>
    Environment:
      SHARED_DIRECTORY:  /share
      SYNC:
    Mounts:
      /share from nfs-share-folder (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kp8p4 (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  nfs-share-folder:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  nfs-share-folder-claim
    ReadOnly:   false
  kube-api-access-kp8p4:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  20s   default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
```

Finally, the pod seems stuck pending:

```
default         nfs-server-76d648b554-4g6kj                   0/1     Pending   0          3m49s
```

We'd like to get this in place for a user that wants to share data with his class via this mechanism. 

(ping @robertej09)

**Comment by julienchastang** [comment] 2023-02-06 18:36
One thing Ana (@robertej09) discovered this AM is the `storageClassName` should be `storageClassName: "cinder-csi"`. That gets us past :

```
  Warning  ProvisioningFailed  8s (x2 over 18s)  persistentvolume-controller  storageclass.storage.k8s.io "standard" not found
```
However, later on, when running the test pod (`test_nfs_mount.yaml`) we unfortunately see another problem with:

```
Events:
  Type     Reason       Age               From               Message
  ----     ------       ----              ----               -------
  Normal   Scheduled    35s               default-scheduler  Successfully assigned default/test-nfs-mount to mvu-test-k8s-node-nf-1
  Warning  FailedMount  4s (x7 over 36s)  kubelet            MountVolume.SetUp failed for volume "nfs-volume" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs 10.233.46.63:/share /var/lib/kubelet/pods/c0f58f07-f981-4f63-99af-cfa81599129f/volumes/kubernetes.io~nfs/nfs-volume
Output: mount: /var/lib/kubelet/pods/c0f58f07-f981-4f63-99af-cfa81599129f/volumes/kubernetes.io~nfs/nfs-volume: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
```

BTW, we have been using the (arbitrary?) KubeSpray IP of `10.233.46.63`.

**Comment by zonca** [comment] 2023-02-06 19:00
thanks!
sure, I am revisiting this, see https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/pull/57

**Comment by zonca** [comment] 2023-02-06 19:03
I confirm I get the same error, will let you know when I have a fix

**Comment by zonca** [comment] 2023-02-06 19:19
you need `nfs-common` on the nodes, unfortunately in the last update of kubespray I removed it by mistake.
I added it back here:
https://github.com/zonca/jetstream_kubespray/commit/43a947f4eba8a6a2c3ebfa152818641e9b483374

So if you want a quick fix, you can ssh into the nodes and run:

    sudo apt install nfs-common

**Comment by zonca** [comment] 2023-02-06 21:22
![](https://github.trello.services/images/mini-trello-icon.png) [Fix NFS tutorial](https://trello.com/c/vhfjMBn4/172-fix-nfs-tutorial)

**Comment by zonca** [comment] 2023-02-06 22:01
ok, this should be fixed now, see also updated tutorial (the only change was the name of the Openstack security group, but I also linked to the Manila tutorial):

https://www.zonca.dev/posts/2023-02-06-nfs-server-kubernetes-jetstream

Please reopen if anything else is broken.

**Closed as completed by zonca** 2023-02-06 22:01 UTC

**Comment by julienchastang** [comment] 2023-02-06 22:43
Yes, the quick fix appears to have worked!

**Comment by julienchastang** [comment] 2023-02-06 23:02
One very small problem:

```
$ bash ../terminal_pod.sh test-nfs-mount
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Error from server (NotFound): namespaces "--" not found
```

I just did a 

```
k exec -it test-nfs-mount -- /bin/bash
```

instead.

**Comment by julienchastang** [comment] 2023-02-06 23:02
Apart from that, yes, it working 🎉 🎉🎉

**Comment by zonca** [comment] 2023-02-06 23:05
right, I'll fix in the tutorial

**Comment by julienchastang** [comment] 2023-02-08 20:55
@zonca one question about the IP, e.g., 

```
# for Kubespray
server: 10.233.46.63
```

Is `10.233.46.63` just an arbitrary IP? Also let's suppose we set up another of these nfs pods on *another* cluster, should the IP not conflict, i.e., select a different IP from the one above? Finally, how can we be sure the IP is valid or will not conflict with another IP somewhere from a network or VM, for example? Is it just trial and error?

**Comment by zonca** [comment] 2023-02-08 21:04
yes, it is arbitrary
You can find what is the range of addresses used by kubernetes, for example, looking at other services

kubectl get services

Yes, choose another address if you want another server.

Consider that you can also use Manila, I have another tutorial about that

**Comment by zonca** [comment] 2023-02-08 21:04
This is an address just internal to the cluster so no worries if you use the same in different clusters

**Comment by julienchastang** [comment] 2023-02-08 21:12
Excellent. Our colleague at a university is already using this NFS server in his classroom so thank you for that, and I am about  to set up a second one.

**Comment by zonca** [comment] 2023-02-15 22:45
thanks for your feedback! I used it to improve the tutorial

**Comment by julienchastang** [comment] 2023-08-15 22:24
Hi @zonca. We recently used the NFS Server feature on one of our JupyterHubs. The instructions worked as advertised but we noticed that `nfs-common` was not installed on the worker node so had to be manually installed. Just a heads up...

**Comment by zonca** [comment] 2023-08-21 20:58
can you check which branch of `jetstream_kubespray` you are using?

it should be inside the bootstrap of the OS:
https://github.com/zonca/jetstream_kubespray/blob/branch_v2.21.0/roles/bootstrap-os/tasks/bootstrap-debian.yml#L49

I will test this on a clean install as soon as I have time.

**Comment by ana-v-espinoza** [comment] 2023-08-29 00:01
Hello Andrea,

Today I provisioned a new cluster for one of our community members and used the opportunity to double check our workflow on this issue. After performing the standard procedure, i.e. Terraform to create infrastructure and Ansible to deploy Kubernetes, I immediately (i.e. without doing anything else) checked whether the `nfs-common` package installed in either our main or worker node. However, it seems like the package isn't installed:

```
ubuntu@<worker-node>:~$ apt list --installed | grep "nfs"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libnfs13/focal,now 4.0.0-1 amd64 [installed,automatic]
```

I've confirmed that we're using the correct branch of `jetstream_kubespray`:
```
[openstack@98f20470cce1 jetstream_kubespray]$ git branch
* branch_v2.21.0
```

Just to be extra sure, I decided to check that the appropriate instruction is where we expect it:
```
[openstack@98f20470cce1 jetstream_kubespray]$ grep -Rnie "nfs-common" roles/bootstrap-os/tasks/
roles/bootstrap-os/tasks/bootstrap-debian.yml:49:    DEBIAN_FRONTEND=noninteractive apt-get install -y python3-minimal nfs-common
```

I did a bit of digging into that file, and it seems like the `bootstrap-debian.yml` playbook [does a check at the beginning](https://github.com/zonca/jetstream_kubespray/blob/99c730dd25e081c1ef75fd91ccd2ee5ccaa4eb0b/roles/bootstrap-os/tasks/bootstrap-debian.yml#L5) of `which python3`. The result of this check is "registered" into the `need_bootstrap` variable, and is then [referenced to determine](https://github.com/zonca/jetstream_kubespray/blob/99c730dd25e081c1ef75fd91ccd2ee5ccaa4eb0b/roles/bootstrap-os/tasks/bootstrap-debian.yml#L52C7-L52C29) whether the "Install python3" instructions, which includes the installation of `nfs-common`, should be executed. Here the `.rc` is referencing the [return code](https://docs.ansible.com/ansible/latest/reference_appendices/common_return_values.html#rc) of the `which` command from earlier.

My guess is that the newest Featured-Ubuntu20 image on Jetstream2 has `python3` installed by default, while older images of that sort did not, so the install command never gets executed on the nodes.

Unfortunately, I didn't save any logs when running `k8s_install.sh` the first time, and my terminal doesn't scroll up that far, so I can't confirm whether this is the case without trying it on a fresh node.

I will be upscaling this cluster to include a few more nodes at the end of the week, and I'll be sure to keep the logs then so I can test my hypothesis.

Best,

Ana V. Espinoza

**Comment by ana-v-espinoza** [comment] 2023-08-30 23:27
Andrea,

Today while deploying a new cluster I tested my hypothesis that the `Install python3` [task](https://github.com/zonca/jetstream_kubespray/blob/99c730dd25e081c1ef75fd91ccd2ee5ccaa4eb0b/roles/bootstrap-os/tasks/bootstrap-debian.yml#L46), which includes the `nfs-common` install, is never executed because `python3` is already a package within newly created nodes.

I logged the ansible output by adding `log_path = ./ansible.log` to the `[defaults]` section of `ansible.cfg`. On inspection of the log file after running `k8s_install.sh`, I see the following:

```
2023-08-30 21:11:28,242 p=312 u=openstack n=ansible | TASK [bootstrap-os : Check if bootstrap is needed] ***************************************************************************************************************************************************************************************
2023-08-30 21:11:28,243 p=312 u=openstack n=ansible | ok: [<main-node>] => {"changed": false, "failed_when_result": false, "rc": 0, "stderr": "Shared connection to <main-node-ip> closed.\r\n", "stderr_lines": ["Shared connection to <main-node-ip> closed."], "stdout": "/usr/bin/python3\r\n", "stdout_lines": ["/usr/bin/python3"]}
2023-08-30 21:11:28,278 p=312 u=openstack n=ansible | ok: [<worker-ip>] => {"changed": false, "failed_when_result": false, "rc": 0, "stderr": "Shared connection to <worker-ip> closed.\r\n", "stderr_lines": ["Shared connection to <worker-ip> closed."], "stdout": "/usr/bin/python3\r\n", "stdout_lines": ["/usr/bin/python3"]}
```

Of particular importance is the `"rc": 0` portion of the output. As discussed above and in my previous comment, this causes the `Install python3` task to never execute.

I still need to up-scale a cluster at the end of the week. When I do so, I'll edit `bootstrap-debian.yml` to include the following snippets, which are based off of the existing `Install python3` tasks:

```yaml
- name: Check if nfs-common is needed
  raw: which mount.nfs
  register: need_nfs
  failed_when: false
  changed_when: false
  # This command should always run, even in check mode
  check_mode: false
  tags:
    - facts
- name: Install nfs-common
  raw:
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y nfs-common
  become: true
  when:
    - need_nfs.rc != 0
```

If this works, I'll open a PR with this update. Of course, the idea here is to separate the two installation tasks.

-- Ana V. E.
