### ISSUE TITLE
GPU Cluster Failing

### ISSUE THREAD

**Issue by julienchastang** [zonca/jupyterhub-deploy-kubernetes-jetstream#88] opened 2024-11-18 23:06 UTC
This issue concerns launching a cluster with one `m3` main node and one `g3` gpu worker node. I followed the instructions [here](https://www.zonca.dev/posts/2024-02-09-kubernetes-gpu-jetstream2) but I did not get very far as the cluster showed problems immediately upon launch before GPU customization. I've been running into issues where after the Kubespray workflow, the cluster ends up looking like the output below. Ana and I spent a long time looking at this but we were never able to get beyond the fact that CoreDNS seems unhappy. I theorize the other problematic pods are the result of the DNS problems, but I am not really sure. Distinguishing between cause and effect has been a challenge during troubleshooting. Just as an experiment, I recreated this workflow, but for CPU only nodes and everything is fine there so this problem is related specifically to the `g3` worker as shown in the output below. Note all problematic pods are on the `g3` worker node. Sshing into the worker node did not reveal any obvious problems as far we could tell, but there again, I am not sure what to look for.

```
kubectl get pods -A -o wide                                                                                                                                                                ab915409e4b2: Mon Nov 18 20:25:42 2024

NAMESPACE       NAME                                           READY   STATUS             RESTARTS         AGE   IP             NODE                  NOMINATED NODE   READINESS GATES
ingress-nginx   ingress-nginx-controller-hjrd6                 1/1     Running            0                57m   10.0.38.162    tm24f-1               <none>           <none>
kube-system     coredns-588bb58b94-rpln8                       1/1     Running            0                57m   10.233.64.2    tm24f-1               <none>           <none>
kube-system     coredns-588bb58b94-rs79b                       0/1     CrashLoopBackOff   16 (2m30s ago)   57m   10.233.65.56   tm24f-k8s-node-nf-1   <none>           <none>
kube-system     csi-cinder-controllerplugin-648ffdc6db-lgx2b   0/6     CrashLoopBackOff   97 (108s ago)    57m   10.233.65.57   tm24f-k8s-node-nf-1   <none>           <none>
kube-system     csi-cinder-nodeplugin-6vxj6                    0/3     CrashLoopBackOff   49 (4m1s ago)    57m   10.0.38.157    tm24f-k8s-node-nf-1   <none>           <none>
kube-system     dns-autoscaler-5b9959d7fc-8wssn                1/1     Running            0                57m   10.233.64.3    tm24f-1               <none>           <none>
kube-system     kube-apiserver-tm24f-1                         1/1     Running            1                59m   10.0.38.162    tm24f-1               <none>           <none>
kube-system     kube-controller-manager-tm24f-1                1/1     Running            1                59m   10.0.38.162    tm24f-1               <none>           <none>
kube-system     kube-flannel-48gkm                             1/1     Running            0                58m   10.0.38.162    tm24f-1               <none>           <none>
kube-system     kube-flannel-p7bq6                             0/1     CrashLoopBackOff   13 (105s ago)    58m   10.0.38.157    tm24f-k8s-node-nf-1   <none>           <none>
kube-system     kube-proxy-5cjfd                               0/1     CrashLoopBackOff   13 (3m30s ago)   58m   10.0.38.157    tm24f-k8s-node-nf-1   <none>           <none>
kube-system     kube-proxy-5mcxv                               1/1     Running            0                58m   10.0.38.162    tm24f-1               <none>           <none>
kube-system     kube-scheduler-tm24f-1                         1/1     Running            1                59m   10.0.38.162    tm24f-1               <none>           <none>
kube-system     nginx-proxy-tm24f-k8s-node-nf-1                1/1     Running            17 (5m39s ago)   58m   10.0.38.157    tm24f-k8s-node-nf-1   <none>           <none>
kube-system     nodelocaldns-9jkm7                             0/1     CrashLoopBackOff   13 (3m6s ago)    57m   10.0.38.157    tm24f-k8s-node-nf-1   <none>           <none>
kube-system     nodelocaldns-w9n4v                             1/1     Running            0                57m   10.0.38.162    tm24f-1               <none>           <none>
kube-system     openstack-cloud-controller-manager-fbdpx       1/1     Running            0                58m   10.0.38.162    tm24f-1               <none>           <none>
kube-system     snapshot-controller-7d445c66c9-fxxl5           0/1     CrashLoopBackOff   16 (3m8s ago)    57m   10.233.65.55   tm24f-k8s-node-nf-1   <none>           <none>
```

cc @ana-v-espinoza @ThomasMGeo

**Comment by zonca** [comment] 2024-11-19 17:43
@julienchastang I am launching a cluster myself to test this.
Given they run the same Ubuntu 22 images, my worry is that the problem is incompatibility between a new version of `nvidia-docker` and Kubespray, see:

https://gitlab.com/jetstream-cloud/general/image-build-pipeline/-/blob/main/ansible/roles/gpu/tasks/Ubuntu.yml

Sorry, still trying to figure this out. There is no separate Ubuntu 22 image for GPU, so `nvidia-docker` should be installed anyway, also in a CPU virtual machine.

Still waiting for Kubespray to finish running, then I'll report back what I get.

**Comment by zonca** [comment] 2024-11-19 18:01
@julienchastang if I do the standard CPU deployment with `Featured-Ubuntu22` with:

    flavor_k8s_master = "4"
    flavor_k8s_node = "11"

so `m3.medium` and `g3.medium`

I don't see any errors.

```
k get pods -A -o wide
NAMESPACE       NAME                                           READY   STATUS    RESTARTS   AGE     IP            NODE                       NOMINATED NODE   READINESS GATES
ingress-nginx   ingress-nginx-controller-cf7p4                 1/1     Running   0          10m     10.1.90.100   kubejetstream-1            <none>           <none>
kube-system     coredns-588bb58b94-69qz9                       1/1     Running   0          9m21s   10.233.65.2   kubejetstream-k8s-node-1   <none>           <none>
kube-system     coredns-588bb58b94-lm6kc                       1/1     Running   0          9m30s   10.233.64.2   kubejetstream-1            <none>           <none>
kube-system     csi-cinder-controllerplugin-648ffdc6db-8dj5m   6/6     Running   0          7m55s   10.233.65.3   kubejetstream-k8s-node-1   <none>           <none>
kube-system     csi-cinder-nodeplugin-brtjw                    3/3     Running   0          7m52s   10.1.90.211   kubejetstream-k8s-node-1   <none>           <none>
kube-system     dns-autoscaler-5b9959d7fc-sxq5w                1/1     Running   0          9m23s   10.233.64.3   kubejetstream-1            <none>           <none>
kube-system     kube-apiserver-kubejetstream-1                 1/1     Running   1          14m     10.1.90.100   kubejetstream-1            <none>           <none>
kube-system     kube-controller-manager-kubejetstream-1        1/1     Running   1          14m     10.1.90.100   kubejetstream-1            <none>           <none>
kube-system     kube-flannel-5mzwg                             1/1     Running   0          11m     10.1.90.100   kubejetstream-1            <none>           <none>
kube-system     kube-flannel-r949z                             1/1     Running   0          11m     10.1.90.211   kubejetstream-k8s-node-1   <none>           <none>
kube-system     kube-proxy-5mwxg                               1/1     Running   0          12m     10.1.90.100   kubejetstream-1            <none>           <none>
kube-system     kube-proxy-kkx8p                               1/1     Running   0          12m     10.1.90.211   kubejetstream-k8s-node-1   <none>           <none>
kube-system     kube-scheduler-kubejetstream-1                 1/1     Running   1          14m     10.1.90.100   kubejetstream-1            <none>           <none>
kube-system     nginx-proxy-kubejetstream-k8s-node-1           1/1     Running   0          12m     10.1.90.211   kubejetstream-k8s-node-1   <none>           <none>
kube-system     nodelocaldns-4997d                             1/1     Running   0          9m18s   10.1.90.100   kubejetstream-1            <none>           <none>
kube-system     nodelocaldns-n9bhd                             1/1     Running   0          9m18s   10.1.90.211   kubejetstream-k8s-node-1   <none>           <none>
kube-system     openstack-cloud-controller-manager-b5s77       1/1     Running   0          11m     10.1.90.100   kubejetstream-1            <none>           <none>
kube-system     snapshot-controller-7d445c66c9-txxfc           1/1     Running   0          7m28s   10.233.65.4   kubejetstream-k8s-node-1   <none>           <none>
```

**Comment by zonca** [comment] 2024-11-19 18:02
@julienchastang what image are you using? should I continue with the GPU setup?

**Comment by ana-v-espinoza** [comment] 2024-11-19 18:15
Hey Andrea,

Thanks for helping us look into this. The image we used was likewise the Featured-Ubuntu22 image.

Julien had noticed that our observations yesterday were suspiciously similar to the ones found in https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/issues/73

You'll notice from the output that Julien pasted shows that even though the `nginx-proxy` Pod is Running, it's restarted 17 times. During the process of troubleshooting, I actually noticed other Pods (or containers in the Pods, for those that have multiple containers) reporting a "Ready" state for a short while before restarting.

**Comment by zonca** [comment] 2024-11-19 18:18
in my test I commented out `supplementary_node_groups = "gpu-node"`, did you have that in your config?
it would be best to just attach your `cluster.tfvars` here.

**Comment by julienchastang** [comment] 2024-11-19 18:21
> what image are you using?

We tried a few: `Featured-Ubuntu22` and also `Featured-Minimal-Ubuntu22`. 

To be clear, I am following [this setup](https://www.zonca.dev/posts/2024-02-09-kubernetes-gpu-jetstream2), so I just followed the regular kubespray workflow. I am not checking out the GPU branch as we did in the past. The only additional modification is I enabled `supplementary_node_groups = "gpu-node"` in `cluster.tfvars`.

> in my test I commented out `supplementary_node_groups = "gpu-node"`, did you have that in your config?

Do you mean comment in or comment out? Bottom line: shouldn't that line be enabled?

**Comment by zonca** [comment] 2024-11-19 18:23
I disabled that line because you said you didn't do any of the GPU-specific config, trying to reproduce your error.
I'm rerunning that with the line enabled, as it should be for a GPU cluster.

**Comment by julienchastang** [comment] 2024-11-19 18:24
> do any of the GPU-specific config

Indeed because we never got to that point. Cluster failed immediately upon launch.

**Comment by julienchastang** [comment] 2024-11-19 18:47
```
# SSH key to use for access to nodes
public_key_path = "~/.ssh/id_rsa.pub"

# image to use for bastion, masters, standalone etcd instances, and nodes
image = "Featured-Ubuntu22"

# user on the node (ex. core on Container Linux, ubuntu on Ubuntu, etc.)
ssh_user = "ubuntu"

# 0|1 bastion nodes
number_of_bastions = 0

#flavor_bastion = "<UUID>"

# standalone etcds
number_of_etcd = 0

# masters
number_of_k8s_masters = 1

# Uncomment and set a previously created IP (or list) for the master nodes
# k8s_master_fips = ["149.xxx.xxx.xxx"]

number_of_k8s_masters_no_etcd = 0

number_of_k8s_masters_no_floating_ip = 0

number_of_k8s_masters_no_floating_ip_no_etcd = 0

flavor_k8s_master = "4"

master_allowed_ports = [{"protocol" = "tcp", "port_range_min" = 80, "port_range_max" = 80, "remote_ip_prefix" = "0.0.0.0/0"}, {"protocol" = "tcp", "port_range_min" = 443, "port_range_max" = 443, "remote_ip_prefix" = "0.0.0.0/0"}]

# nodes
# for debugging purposes we can create nodes with floating ip
# in production better use nodes with no floating ip

number_of_k8s_nodes = 0

number_of_k8s_nodes_no_floating_ip = 1

flavor_k8s_node = "11"

# # Uncomment when all nodes will be GPU nodes
# # If you wish to use this var for another reason, add the ansible groups as a comma seperated list
# # E.g "additional-group-1,additional-group2,etc"
supplementary_node_groups = "gpu-node"

# BEGIN HYBRID CLUSTER CONFIG

# # Set to true by default, but we make it explicit here
# port_security_enabled = true

# # Must be uncommented and set to 0 to use the k8s_nodes variable
# number_of_k8s_nodes = 0
# number_of_k8s_nodes_no_floating_ip = 0

# # "<cluster-name>-k8s-node-" will be prepended to each key name and used to create the instance name.
# # E.g the first item below would result in an instanced named "<cluster-name>-k8s-node-nf-cpu-1"
# # For a full list of options see ./contrib/terraform/openstack/README.md#k8s_nodes
# k8s_nodes = {
#   "nf-cpu-1" = {
#     "az" = "nova"
#     "flavor": "4"
#     "floating_ip": false
#   },
#   "nf-cpu-2" = {
#     "az" = "nova"
#     "flavor": "4"
#     "floating_ip": false
#   },
#   "nf-gpu-1" = {
#     "az" = "nova"
#     "flavor": "10"
#     "floating_ip": false
#     "extra_groups": "gpu-node"
#   },
#   "nf-gpu-2" = {
#     "az" = "nova"
#     "flavor": "10"
#     "floating_ip": false
#     "extra_groups": "gpu-node"
#   },
# }

# END HYBRID CLUSTER CONFIG

# GlusterFS
# either 0 or more than one
#number_of_gfs_nodes_no_floating_ip = 0
#gfs_volume_size_in_gb = 150
# Container Linux does not support GlusterFS
#image_gfs = "<image name>"
# May be different from other nodes
#ssh_user_gfs = "ubuntu"
#flavor_gfs_node = "<UUID>"

# Jetstream 2
external_net = "3fe22c05-6206-4db2-9a13-44f04b6796e6"

floatingip_pool = "public"

# list of availability zones available in your OpenStack cluster
# IU
az_list = ["nova"]
az_list_node = ["nova"]

bastion_allowed_remote_ips = ["0.0.0.0/0"]

# if you only access from a subset of IPs, set this accordingly for
# more security
k8s_allowed_remote_ips = ["0.0.0.0/0"]

# have Kubernetes traffic use the internal IP
use_access_ip = 0

# This is now un-necessary because we use the auto_allocated_network which is preconfigured
# network_dns_domain = "xxx000000.projects.jetstream-cloud.org."

# Reuse the auto allocated router, we do not want to waste floating IPs by having un-necessary routers
# REPLACE with your `auto_allocated_router` ID (use `openstack router list`)
router_id = "15cc195f-02d4-4d9b-ae24-5b2e9e52a13a"

# Reuse the auto-allocated network
use_existing_network = true
network_name = "auto_allocated_network"

# Default subnetpool ID for JetStream2; Let neutron (openstack) do the CIDR
# book-keeping for you
subnetpool_id = "be988956-1bfb-4828-b511-a58229fbd4ac"

```

**Comment by ana-v-espinoza** [comment] 2024-11-19 19:24
> in my test I commented out `supplementary_node_groups = "gpu-node"`, did you have that in your config? it would be best to just attach your `cluster.tfvars` here.

As Julien showed, we indeed had that un-commented in our config. That's interesting, and leads me to believe there's some funny business going on with the nvidia-container-runtime that's defined [here](https://github.com/zonca/jetstream_kubespray/blob/branch_v2.21.0/inventory/kubejetstream/group_vars/gpu-node/containderd.yml), which used to live [here](https://github.com/zonca/jetstream_kubespray/blob/branch_v2.18.0_gpu/inventory/kubejetstream/group_vars/all/containerd.yml) (linked is the v2.18.0_gpu branch, for reference).

Doing a bit of detective work, the files are nearly identical:
```
➜  all git:(737b667ee) diff containerd.yml /tmp/containerd-2.21.0.yml
17c17
<       BinaryName : '"/usr/bin/nvidia-container-runtime"'
---
>     BinaryName : '"/usr/bin/nvidia-container-runtime"'
18a19
>
37a39
> ## set "name": "url". insecure url must be started http://
40,41c42,43
< #   - mirror.registry.io
< #   - 172.19.16.11:5000
---
> #   "localhost": "http://127.0.0.1"
> #   "172.19.16.11:5000": "http://172.19.16.11:5000"
51a54
>
```
The only differences are some indentation and some lines that are commented out anyway.

I double checked yesterday that the correct container runtime was being used with a `containerd config dump`. I don't have that output anymore however.

All this to say: Everything from the Kubespray end is functioning as expected, but the environment (Ubuntu22 vs Ubuntu20, when this workflow was first tested) has changed, so the root cause of this issue is likely related to that.

**Comment by zonca** [comment] 2024-11-19 20:10
ok, I can reproduce the issue, I agree, it must be something with `nvidia-container-runtime`

```
k get pods -A -o wide
NAMESPACE       NAME                                           READY   STATUS             RESTARTS         AGE   IP             NODE                       NOMINATED NODE   READINESS GATES
ingress-nginx   ingress-nginx-controller-wc8sj                 1/1     Running            0                44m   10.1.90.62     kubejetstream-1            <none>           <none>
kube-system     coredns-588bb58b94-24kj7                       0/1     CrashLoopBackOff   12 (2m25s ago)   43m   10.233.65.39   kubejetstream-k8s-node-1   <none>           <none>
kube-system     coredns-588bb58b94-rg52t                       1/1     Running            0                43m   10.233.64.2    kubejetstream-1            <none>           <none>
kube-system     csi-cinder-controllerplugin-648ffdc6db-92jfq   0/6     CrashLoopBackOff   61 (2m57s ago)   41m   10.233.65.38   kubejetstream-k8s-node-1   <none>           <none>
kube-system     csi-cinder-nodeplugin-mqflw                    0/3     CrashLoopBackOff   37 (113s ago)    41m   10.1.90.74     kubejetstream-k8s-node-1   <none>           <none>
kube-system     dns-autoscaler-5b9959d7fc-srrr8                1/1     Running            0                43m   10.233.64.3    kubejetstream-1            <none>           <none>
kube-system     kube-apiserver-kubejetstream-1                 1/1     Running            1                49m   10.1.90.62     kubejetstream-1            <none>           <none>
kube-system     kube-controller-manager-kubejetstream-1        1/1     Running            1                49m   10.1.90.62     kubejetstream-1            <none>           <none>
kube-system     kube-flannel-b7p4l                             1/1     Running            0                45m   10.1.90.62     kubejetstream-1            <none>           <none>
kube-system     kube-flannel-dbrf5                             0/1     CrashLoopBackOff   11 (3m30s ago)   45m   10.1.90.74     kubejetstream-k8s-node-1   <none>           <none>
kube-system     kube-proxy-s25v6                               1/1     Running            14 (3m45s ago)   47m   10.1.90.74     kubejetstream-k8s-node-1   <none>           <none>
kube-system     kube-proxy-s5dvl                               1/1     Running            0                47m   10.1.90.62     kubejetstream-1            <none>           <none>
kube-system     kube-scheduler-kubejetstream-1                 1/1     Running            1                49m   10.1.90.62     kubejetstream-1            <none>           <none>
kube-system     nginx-proxy-kubejetstream-k8s-node-1           1/1     Running            15 (9m8s ago)    46m   10.1.90.74     kubejetstream-k8s-node-1   <none>           <none>
kube-system     nodelocaldns-c56wd                             1/1     Running            0                43m   10.1.90.62     kubejetstream-1            <none>           <none>
kube-system     nodelocaldns-vlzps                             1/1     Running            10 (6m47s ago)   43m   10.1.90.74     kubejetstream-k8s-node-1   <none>           <none>
kube-system     openstack-cloud-controller-manager-lv9bp       1/1     Running            0                45m   10.1.90.62     kubejetstream-1            <none>           <none>
kube-system     snapshot-controller-7d445c66c9-n8rd9           1/1     Running            10 (6m59s ago)   41m   10.233.65.36   kubejetstream-k8s-no
```

**Comment by zonca** [comment] 2024-11-19 21:49
@julienchastang @ana-v-espinoza I just tested with `Featured-Ubuntu20` and it worked fine 

```
nvidia-container-runtime --version
NVIDIA Container Runtime version 1.13.5
commit: 6b8589dcb4dead72ab64f14a5912886e6165c079
spec: 1.1.0-rc.2

runc version 1.1.4
commit: v1.1.4-0-g5fd4c4d1
spec: 1.0.2-dev
go: go1.17.10
libseccomp: 2.5.4
```

My guess is that our older Kubespray supports only an older version of nvidia container runtime

**Comment by zonca** [comment] 2024-11-19 21:50
```
k get pods -A -o wide
NAMESPACE       NAME                                           READY   STATUS    RESTARTS   AGE     IP            NODE                       NOMINATED NODE   READINESS GATES
ingress-nginx   ingress-nginx-controller-pl2p8                 1/1     Running   0          11m     10.1.90.52    kubejetstream-1            <none>           <none>
kube-system     coredns-588bb58b94-7szcx                       1/1     Running   0          10m     10.233.64.2   kubejetstream-1            <none>           <none>
kube-system     coredns-588bb58b94-b2vj8                       1/1     Running   0          10m     10.233.65.2   kubejetstream-k8s-node-1   <none>           <none>
kube-system     csi-cinder-controllerplugin-648ffdc6db-9qfv6   6/6     Running   0          8m34s   10.233.65.3   kubejetstream-k8s-node-1   <none>           <none>
kube-system     csi-cinder-nodeplugin-xmhvn                    3/3     Running   0          8m31s   10.1.90.197   kubejetstream-k8s-node-1   <none>           <none>
kube-system     dns-autoscaler-5b9959d7fc-pwxql                1/1     Running   0          10m     10.233.64.3   kubejetstream-1            <none>           <none>
kube-system     kube-apiserver-kubejetstream-1                 1/1     Running   1          15m     10.1.90.52    kubejetstream-1            <none>           <none>
kube-system     kube-controller-manager-kubejetstream-1        1/1     Running   1          15m     10.1.90.52    kubejetstream-1            <none>           <none>
kube-system     kube-flannel-qzzrt                             1/1     Running   0          12m     10.1.90.197   kubejetstream-k8s-node-1   <none>           <none>
kube-system     kube-flannel-sp5dr                             1/1     Running   0          12m     10.1.90.52    kubejetstream-1            <none>           <none>
kube-system     kube-proxy-g85bd                               1/1     Running   0          13m     10.1.90.52    kubejetstream-1            <none>           <none>
kube-system     kube-proxy-gh8dj                               1/1     Running   0          13m     10.1.90.197   kubejetstream-k8s-node-1   <none>           <none>
kube-system     kube-scheduler-kubejetstream-1                 1/1     Running   1          15m     10.1.90.52    kubejetstream-1            <none>           <none>
kube-system     nginx-proxy-kubejetstream-k8s-node-1           1/1     Running   0          12m     10.1.90.197   kubejetstream-k8s-node-1   <none>           <none>
kube-system     nodelocaldns-6ph5v                             1/1     Running   0          9m57s   10.1.90.52    kubejetstream-1            <none>           <none>
kube-system     nodelocaldns-z7fqx                             1/1     Running   0          9m57s   10.1.90.197   kubejetstream-k8s-node-1   <none>           <none>
kube-system     openstack-cloud-controller-manager-xbdb4       1/1     Running   0          11m     10.1.90.52    kubejetstream-1            <none>           <none>
kube-system     snapshot-controller-7d445c66c9-2cthz           1/1     Running   0          8m7s    10.233.65.4   kubejetstream-k8s-node-1   <none>           <none>
```

**Comment by zonca** [comment] 2024-11-19 21:53
actually this won't work, Ubuntu 20 featured images do not have support for GPU:

https://docs.jetstream-cloud.org/faq/gpu/#ubuntu-20-does-not-work-with-my-gpu

**Comment by zonca** [comment] 2024-11-19 22:02
here is on featured ubuntu 22:

```
nvidia-container-runtime --version
NVIDIA Container Runtime version 1.13.5
commit: 6b8589dcb4dead72ab64f14a5912886e6165c079
spec: 1.1.0-rc.2

runc version 1.1.12-0ubuntu2~22.04.1
spec: 1.0.2-dev
go: go1.21.1
libseccomp: 2.5.3
```

**Comment by zonca** [comment] 2024-11-19 23:07
Trying to debug what is going on in the Kubernetes deployment with Ubuntu 22 Featured.

logs of kube flannel

```
Error from server (InternalError): Internal error occurred: Authorization error (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)
```

**Comment by zonca** [comment] 2024-11-20 00:18
I switched the networking plugin to calico, in the hope of getting a bit more insight, same behavior,
as you already noticed, it seems like the first pod to fail is `coredns`

```
k get pods -A -o wide                                          
NAMESPACE       NAME                                           READY   STATUS             RESTARTS         AGE     IP               NODE                       NOMINATED NODE   READINESS
 GATES                                                                                                                                                                                   
ingress-nginx   ingress-nginx-controller-s65km                 1/1     Running            0                11m     10.1.90.75       kubejetstream-1            <none>           <none>   
kube-system     calico-kube-controllers-75748cc9fd-7w4j8       1/1     Running            5 (5m17s ago)    12m     10.233.70.152    kubejetstream-k8s-node-1   <none>           <none>
kube-system     calico-node-lf4wv                              1/1     Running            2 (13m ago)      13m     10.1.90.75       kubejetstream-1            <none>           <none>
kube-system     calico-node-zqv7z                              1/1     Running            9 (6m6s ago)     13m     10.1.90.254      kubejetstream-k8s-node-1   <none>           <none>
kube-system     coredns-588bb58b94-rhc8x                       0/1     CrashLoopBackOff   7 (99s ago)      9m53s   10.233.70.160    kubejetstream-k8s-node-1   <none>           <none>
kube-system     coredns-588bb58b94-zpvfk                       1/1     Running            0                10m     10.233.114.193   kubejetstream-1            <none>           <none>   
kube-system     csi-cinder-controllerplugin-648ffdc6db-tpjrb   6/6     Running            48 (3m16s ago)   8m23s   10.233.70.159    kubejetstream-k8s-node-1   <none>           <none>   
kube-system     csi-cinder-nodeplugin-hwr67                    3/3     Running            21 (3m34s ago)   8m19s   10.1.90.254      kubejetstream-k8s-node-1   <none>           <none>   
kube-system     dns-autoscaler-5b9959d7fc-gp4kf                1/1     Running            0                9m54s   10.233.114.194   kubejetstream-1            <none>           <none>
kube-system     kube-apiserver-kubejetstream-1                 1/1     Running            1                17m     10.1.90.75       kubejetstream-1            <none>           <none>
kube-system     kube-controller-manager-kubejetstream-1        1/1     Running            1                17m     10.1.90.75       kubejetstream-1            <none>           <none>
kube-system     kube-proxy-2nxmd                               1/1     Running            9 (2m14s ago)    15m     10.1.90.254      kubejetstream-k8s-node-1   <none>           <none>
kube-system     kube-proxy-64lnd                               1/1     Running            0                15m     10.1.90.75       kubejetstream-1            <none>           <none>
kube-system     kube-scheduler-kubejetstream-1                 1/1     Running            1                17m     10.1.90.75       kubejetstream-1            <none>           <none>
kube-system     nginx-proxy-kubejetstream-k8s-node-1           1/1     Running            9 (3m19s ago)    14m     10.1.90.254      kubejetstream-k8s-node-1   <none>           <none>
kube-system     nodelocaldns-cwvz9                             1/1     Running            6 (5m46s ago)    9m54s   10.1.90.254      kubejetstream-k8s-node-1   <none>           <none>
kube-system     nodelocaldns-s7rcf                             1/1     Running            0                9m54s   10.1.90.75       kubejetstream-1            <none>           <none>
kube-system     openstack-cloud-controller-manager-6qm77       1/1     Running            0                12m     10.1.90.75       kubejetstream-1            <none>           <none>
kube-system     snapshot-controller-7d445c66c9-bp6cp           1/1     Running            7 (4m34s ago)    7m53s   10.233.70.156    kubejetstream-k8s-node-1   <none>           <none>
```

**Comment by zonca** [comment] 2024-11-20 02:57
@julianpistorius any suggestion on how the NVidia container runtime (or the GPU node itself) can cause networking issues in Kubernetes?

It seems like Kubespray works fine deploying on CPU but fails on Featured Ubuntu 22 with what appears to be networking issues, it looks like the network plugin fails and then a lot of other services start failing as well.
Strangely enough if we run Featured Ubuntu 20 it seems to not show this problem, even if we run the Nvidia container runtime, however that doesn't work as solution because Ubuntu 20 does not support GPUs anymore.

However I am not very confident we can fix this issue, I think the only way would be to upgrade Kubespray and hope that it is just some incompatibility between the container runtime 1.13.5 which was released in August 2023 and Kubespray  1.25.6, released in December 2022.

**Comment by ana-v-espinoza** [comment] 2024-11-20 16:26
Hey Andrea,

I did some searching and found this issue that smells suspiciously like what we're running into:
https://github.com/k3s-io/k3s/issues/7130

They did their own digging and found this issue:
https://github.com/NVIDIA/nvidia-container-toolkit/issues/28#issuecomment-1201243587

It seems that the "fix" in this case was a change to the `containerd` configuration. When adding the additional containerd runtime, they also added the following option:
```
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  systemdCgroup = true
```

In Kubespray, that would be equivalent to updating this entry:
https://github.com/zonca/jetstream_kubespray/blob/6ba36564107c34a6261f2ae44d05aa344277e10e/inventory/kubejetstream/group_vars/gpu-node/containderd.yml#L16

I'm going to test this and get back to you.

**Comment by ana-v-espinoza** [comment] 2024-11-20 17:49
I'm seeing tentative success with this fix!

```
[openstack@eab34f71dfe5 bin]$ kubectl get pods -A -o wide --sort-by="spec.nodeName"
NAMESPACE       NAME                                           READY   STATUS    RESTARTS         AGE   IP             NODE                  NOMINATED NODE   READINESS GATES
... (main node pods) ...
kube-system     csi-cinder-nodeplugin-7jz6c                    3/3     Running   15 (11m ago)     17m   10.0.38.190    tm24f-k8s-node-nf-1   <none>           <none>
kube-system     kube-proxy-cpsjs                               1/1     Running   6 (12m ago)      18m   10.0.38.190    tm24f-k8s-node-nf-1   <none>           <none>
kube-system     kube-flannel-7mksd                             1/1     Running   7 (10m ago)      18m   10.0.38.190    tm24f-k8s-node-nf-1   <none>           <none>
kube-system     nginx-proxy-tm24f-k8s-node-nf-1                1/1     Running   4 (10m ago)      18m   10.0.38.190    tm24f-k8s-node-nf-1   <none>           <none>
kube-system     nodelocaldns-895jn                             1/1     Running   5 (13m ago)      17m   10.0.38.190    tm24f-k8s-node-nf-1   <none>           <none>
kube-system     csi-cinder-controllerplugin-648ffdc6db-bc5sb   6/6     Running   36 (8m58s ago)   17m   10.233.65.22   tm24f-k8s-node-nf-1   <none>           <none>
kube-system     coredns-588bb58b94-s58n6                       1/1     Running   6 (11m ago)      17m   10.233.65.21   tm24f-k8s-node-nf-1   <none>           <none>
kube-system     snapshot-controller-7d445c66c9-bwbk6           1/1     Running   6 (12m ago)      16m   10.233.65.20   tm24f-k8s-node-nf-1   <none>           <none>
```

You'll notice that there are still some restarts. I had initially made a typo in the containerd config (systemdCgroup***s*** vs systemdCgroup, no trailing "s"), so they were initially failing. I manually edited `/etc/containerd/config.toml` and restarted the service with a `systemctl restart containerd` to reload the correct config, and the Pods slowly came online.

I'm going to rerun the ansible playbook with the ~~typo to the correction~~ correction to the typo and get a "fresh" install, confirm it works, then continue with the GPU configuration (k8s dev plugin, testing a gpu enabled pod, installing JupyterHub, etc.)

Here's my `git diff` to show the changes:

```diff
[openstack@eab34f71dfe5 jetstream_kubespray]$ git diff
diff --git a/inventory/kubejetstream/cluster.tfvars b/inventory/kubejetstream/cluster.tfvars
index 77ed5a714..8e5af8b38 100644
--- a/inventory/kubejetstream/cluster.tfvars
+++ b/inventory/kubejetstream/cluster.tfvars
@@ -35,16 +35,16 @@ master_allowed_ports = [{"protocol" = "tcp", "port_range_min" = 80, "port_range_
 # for debugging purposes we can create nodes with floating ip
 # in production better use nodes with no floating ip

-number_of_k8s_nodes = 1
+number_of_k8s_nodes = 0

-number_of_k8s_nodes_no_floating_ip = 0
+number_of_k8s_nodes_no_floating_ip = 1

-flavor_k8s_node = "4"
+flavor_k8s_node = "11"

 # # Uncomment when all nodes will be GPU nodes
 # # If you wish to use this var for another reason, add the ansible groups as a comma seperated list
 # # E.g "additional-group-1,additional-group2,etc"
-# supplementary_node_groups = "gpu-node"
+supplementary_node_groups = "gpu-node"

 # BEGIN HYBRID CLUSTER CONFIG

diff --git a/inventory/kubejetstream/group_vars/gpu-node/containderd.yml b/inventory/kubejetstream/group_vars/gpu-node/containderd.yml
index 4c661d1dd..402c33334 100644
--- a/inventory/kubejetstream/group_vars/gpu-node/containderd.yml
+++ b/inventory/kubejetstream/group_vars/gpu-node/containderd.yml
@@ -15,6 +15,7 @@ containerd_runc_runtime:
   root: ""
   options:
     BinaryName : '"/usr/bin/nvidia-container-runtime"'
+    systemdCgroup: 'true'
```

@zonca , could you test these changes as well to confirm it works on your end too?

**Comment by zonca** [comment] 2024-11-20 17:57
Of course! Can you make a pull request on the repository?

**Comment by zonca** [comment] 2024-11-21 03:43
@ana-v-espinoza the initial deployment using https://github.com/zonca/jetstream_kubespray/pull/31 works great:

```
k get pods -A
NAMESPACE       NAME                                           READY   STATUS    RESTARTS   AGE
ingress-nginx   ingress-nginx-controller-4dt7v                 1/1     Running   0          5h2m
kube-system     coredns-588bb58b94-d72db                       1/1     Running   0          5h1m
kube-system     coredns-588bb58b94-h68xr                       1/1     Running   0          5h1m
kube-system     csi-cinder-controllerplugin-648ffdc6db-rs28t   6/6     Running   0          4h59m
kube-system     csi-cinder-nodeplugin-k7kxj                    3/3     Running   0          4h59m
kube-system     dns-autoscaler-5b9959d7fc-6h6dg                1/1     Running   0          5h1m
kube-system     kube-apiserver-kubejetstream-1                 1/1     Running   1          5h6m
kube-system     kube-controller-manager-kubejetstream-1        1/1     Running   1          5h6m
kube-system     kube-flannel-5mm6p                             1/1     Running   0          5h3m
kube-system     kube-flannel-hsg8j                             1/1     Running   0          5h3m
kube-system     kube-proxy-gbmr5                               1/1     Running   0          5h4m
kube-system     kube-proxy-jtzsw                               1/1     Running   0          5h4m
kube-system     kube-scheduler-kubejetstream-1                 1/1     Running   1          5h6m
kube-system     nginx-proxy-kubejetstream-k8s-node-1           1/1     Running   0          5h4m
kube-system     nodelocaldns-25zfs                             1/1     Running   0          5h1m
kube-system     nodelocaldns-266vd                             1/1     Running   0          5h1m
kube-system     openstack-cloud-controller-manager-blcbr       1/1     Running   0          5h3m
kube-system     snapshot-controller-7d445c66c9-9zgsf           1/1     Running   0          4h59m
```

**Comment by zonca** [comment] 2024-11-21 05:37
@ana-v-espinoza I tested all the way to JupyterHub and Tensorflow, everything works.
Thanks for finding a fix for this!

**Closed as completed by zonca** 2024-11-21 05:37 UTC
